[project]
name = "ansible-playbook"
version = "0.1.0"
description = "Ansible Playbook"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "ansible>=11.0.0",
  "ansible-lint>=25.0.0",
]
