---
- name: Install useful python packages via pipx
  community.general.pipx:
    name: "{{ item }}"
    state: latest
  loop:
    - tldr # man
    - httpie # curl
  when: false # See https://github.com/pypa/pipx/issues/1669
